Vagrant.configure("2") do |config|
  # CHANGED: 'generic/windows10' does not exist. 
  # Using 'gusztavvargadr/windows-10' which is a standard community box for Win10.
  config.vm.box = "gusztavvargadr/windows-10"
  
  # --- DISABLE SMB SHARED FOLDERS ---
  # We disable this to prevent Vagrant from asking for your local machine's credentials.
  # We don't need file syncing because we download artifacts via HTTP from the KDC.
  config.vm.synced_folder ".", "/vagrant", disabled: true

  config.vm.network "public_network"
  config.vm.hostname = "win-client"
  
  # Windows requires WinRM for communication (Default for this box)
  config.vm.communicator = "winrm"

  config.vm.provider "hyperv" do |hv|
    hv.vmname = "win-client"
    hv.memory = 4096
    hv.maxmemory = 4096
    hv.cpus = 2
    hv.enable_virtualization_extensions = true
    # Linked clones speed up imports if supported by the box
    hv.linked_clone = true 
  end

  # Read KDC IP from the parent folder
  kdc_ip = "127.0.0.1"
  if File.exist?('../.kdc_ip')
    kdc_ip = File.read('../.kdc_ip').strip
  end

  # Run the PowerShell provision script
  config.vm.provision "shell", path: "provision.ps1", args: [kdc_ip]
end
